project:
  type: website
  output-dir: _site

website:
  title: "Deep Learning Lectures"
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://www.github.com/jeremyfix/deeplearning-lectures
          - text: Report a bug
            href: https://github.com/jeremyfix/deeplearning-lectures/issues/new/choose
    left:
      - text: "Home"
        file: index.qmd
      - text: "Pytorch"
        menu:
          - text: "PyTorch FashionMNIST"
            file: pytorch/fashionMNIST/index.qmd
          - text: "PyTorch Object Detection"
            file: pytorch/object-detection/index.qmd
          - text: "Semantic segmenation on Stanford-2D-3D S"
            file: pytorch/segmentation/index.qmd
          - text: "Automatic Speech Recognition on Mozilla Common Voice"
            file: pytorch/asr/index.qmd
          - text: "Deep Convolutional Generative Adversarial Networks"
            file: pytorch/gan/index.qmd
      - text: "Keras"
        menu:
          - text: "First steps in Keras: classifying handwritten digits(MNIST)"
            file: keras/mnist.qmd
          - text: "Keras CIFAR"
            file: keras/cifar.qmd
      - text: "Resources"
        menu:
          - text: "Argparse"
            file: argparse.qmd

  sidebar:
    style: "docked"
    contents:
      - section: "Getting Started"
        contents:
          - index.qmd
      - section: "Pytorch"
        contents:
          - pytorch/fashionMNIST/index.qmd
          - pytorch/object-detection/index.qmd
          - pytorch/segmentation/index.qmd
          - pytorch/asr/index.qmd
          - pytorch/gan/index.qmd
      - section: "Keras"
        contents:
          - keras/mnist.qmd
          - keras/cifar.qmd
      - section: "Resources"
        contents:
          - argparse.qmd

execute:
  enabled: false
  
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-copy: true
    code-line-numbers: false
    css: styles.css
    link-citations: true

bibliography: biblio.bib
csl: apsa.csl
