data:
  batch_size: 32
  normalize: False
  valid_ratio: 0.2
  num_workers: 4
  class: "ImageDataset"
  params:
    root_dir: '.'

optim:
  algo: Adam
  params:
    lr: 0.001

nepochs: 20

logging:
  # wandb: 
  #   project: sample_project
  #   entity: sample_entity
  logdir: "./logs"  # Better to provide the fullpath, especially on the cluster

model:
  class: "RealNGP"
  params:
    n_hidden_units: 128
    n_hidden_layers: 6
    pos_encoding:
      class: "Positional"
      params: 
        L: 10
