data:
  batch_size: 32
  normalize: True
  valid_ratio: 0.2
  num_workers: 4
  class: "ImageDataset"
  params:
    root_dir: './images'

optim:
  algo: Adam
  params:
    lr: 0.01

nepochs: 200

logging:
  # wandb: 
  #   project: sample_project
  #   entity: sample_entity
  logdir: "./logs"  # Better to provide the fullpath, especially on the cluster

model:
  class: "RealNGP"
  params:
    n_hidden_units: 64
    n_hidden_layers: 4
    pos_encoding:
      class: "Positional"
      params: 
        L: 10
