[project]
name = "asrlab"
version = "0.0.1"

dependencies = [
    "torch>=2.0",
    "torchaudio",
    "tqdm>=4.65.0",
    "numpy>=2.2.4",
    "deepcs>=0.2.10",
    "tensorboard",
    "albumentations>=2.0.5",
    "matplotlib",
    "onnx>=1.17",
    "onnxruntime-gpu>=1.19.2",
    "onnxscript",
    "requests>=2.32.3",
    "PyYAML>=6.0",
    "multiprocess>=0.70.17",
    "wandb>=0.19.9"
]

[options]
package_dir = "asrlab"
