name: Pytorch semantic segmentation lab test
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'   
      - name: Install the dependencies
        working-directory: ./LabsSolutions/01-pytorch-segmentation
        run: python -m pip install -r requirements.txt
      - name: Test implementation
        run: python test_implementation.py
        
