name: Pytorch GAN lab test
on: [push]
jobs:
  test-03-GAN:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'   
      - name: Install the dependencies
        working-directory: ./LabsSolutions/03-pytorch-gan
        run: python -m pip install -r requirements.txt
      - name: Test implementation
        working-directory: ./LabsSolutions/03-pytorch-gan
        run: python test_implementation.py
        
